[package]
name = "littlefs-sys"
version = "0.1.0"
authors = ["Brandon Edens <brandonedens@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.43"

[build-dependencies]
bindgen = "0.43.1"
cc = "1.0.25"
